# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout private action
        uses: actions/checkout@v2
        with:
          # This is the actual action we will execute
          repository: EnterpriseDB/edb-actions
          ssh-key: ${{ secrets.SSH_KEY }}
          ref: "main"
          path: .github/actions/edb-actions

      - name: switch branch
        run: |
          git pull
          git checkout feat/output-metrics
        working-directory: ./.github/actions/edb-actions

      # Optional step to verify checkout was successfully executed
      - name: varify
        run: |
          ls -la ./.github/actions/edb-actions
      # This step actuall loads the edb custom action and executes it
      - name: run private action
        id: edbaction
        uses: ./.github/actions/edb-actions
        with:
          module_id: "github-jira-sync"
          strategy: "unidirectional"
          transition_map: '{ "start": "dev start", "review": "review start", "done": "test start" }'
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: "https://edbtest.atlassian.net"

      - name: test action
        uses: leo-jin-edb/edb-google-connector-action@main
        env:
          GOOG_SA_EMAIL: ${{ secrets.GOOG_SA_EMAIL}}
          GOOG_SA_KEY: ${{ secrets.GOOG_SA_KEY }}
        with:
          metrics: ${{ steps.edbaction.outputs.metrics}}
